# Generated by Django 5.2.4 on 2025-08-31 14:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projectmedia_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmedia',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
