# Generated by Django 5.2.4 on 2025-09-04 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='live_url',
        ),
    ]
