# fly.toml app configuration file for your Django application
# See https://fly.io/docs/reference/configuration/ for more details

app = "your-app-name"  # Replace with your Fly.io app name
primary_region = "lhr"  # Choose a region close to you (e.g., lhr for London, ord for Chicago)

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"
  PYTHONUNBUFFERED = "1"
  DJANGO_SETTINGS_MODULE = "portfolio.settings"
  # Debug settings
  DEBUG = "False"
  # Database
  DATABASE_URL = "postgres://"  # Will be set by Fly.io PostgreSQL
  # Security
  ALLOWED_HOSTS = "*"  # Will be updated during deployment
  # Email settings (configure these via fly secrets)
  # EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
  # DEFAULT_FROM_EMAIL = "noreply@yourdomain.com"
  # SERVER_EMAIL = "server@yourdomain.com"
  # CORS settings
  CORS_ALLOWED_ORIGINS = ""  # Add your frontend URL(s) here

[deploy]
  strategy = "bluegreen"

[[services]]
  http_checks = []
  internal_port = 8000
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [services.http_options]
    response_timeout = 300

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = 15
    restart_limit = 0
    timeout = 300
