# Generated by Django 5.2.4 on 2025-09-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_about_cv_alter_herosection_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='hiring_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
