# Generated by Django 5.2.4 on 2025-09-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_image_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='link',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
