# Generated by Django 5.2.4 on 2025-08-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('category', models.CharField(choices=[('language', 'Language'), ('framework', 'Framework'), ('database', 'Database'), ('tool', 'Tool'), ('other', 'Other')], default='other', max_length=50)),
                ('proficiency', models.PositiveIntegerField(blank=True, help_text='0-100', null=True)),
                ('icon_key', models.CharField(blank=True, help_text='Key from devicon library (ex: python, react)', max_length=140, null=True)),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='skills/icons/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-proficiency', 'name'],
            },
        ),
    ]
