# Generated by Django 5.2.4 on 2025-08-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_skillreference_alter_skill_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillreference',
            name='id_icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
