# Generated by Django 5.2.4 on 2025-08-29 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_skill_owner_alter_skill_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='skill',
            name='owner',
        ),
    ]
