# Generated by Django 5.2.4 on 2025-09-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0005_alter_skill_unique_together_remove_skill_owner'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('reference',), name='unique_reference_in_skill'),
        ),
    ]
